# Generated by Django 5.1.5 on 2025-02-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='username',
            field=models.TextField(default='Guest'),
        ),
    ]
